spring:
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # ?? ??? ??
      connection-timeout: 30000 # ???? ?? ?? ???? ?? ?? (ms)
      max-lifetime: 1800000 # ???? ?? ?? (ms)

    # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경 추천)
      # create: 기존 테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      ddl-auto: none
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect
  # flyway ??
  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???)
    locations: classpath:db/migration

# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# 내장 웹 서버 설정
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
