spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:dummy}
      chat:
        options:
          model: claude-sonnet-4-5-20250929  # or claude-opus-4.1
          temperature: 0.7
          max-tokens: 4096
    ollama:
      base-url: http://localhost:11434  # OLLAMA 서버 주소
      embedding:
        model: nomic-embed-text
      chat:
        options:
          model: qwen2.5:3b              # 사용할 모델
          temperature: 0.7               # 창의성 (0.0 ~ 1.0)
          num-predict: 1000              # 최대 생성 토큰 수# 로깅 설정 (선택사항)
      timeout: 10000s
    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768       # qwen2.5:0.3b -> 896
        distance-type: cosine  # COSINE_DISTANCE → cosine
        index-type: hnsw

  datasource:
    url: jdbc:postgresql://localhost:5432/teamsparta_vector
    username: rtan
    password: sparta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    #baseline-on-migrate: true
    locations: classpath:db.migration



# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# 내장 웹 서버 설정
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
